# Datasource JNDI WildFly
spring.datasource.jndi-name=java:/jdbc/immobilierDS

# Hibernate
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Optimisations Hibernate
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.fetch_size=50
spring.jpa.properties.hibernate.default_batch_fetch_size=100

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false

# Thymeleaf
spring.thymeleaf.cache=true

# Logs
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.security=WARN

# stockage fichiers
app.storage.directory=/opt/immobilier/dossiers

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nahouadioni19@gmail.com
spring.mail.password=fxsfahnjubmyehzb
#spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.WildFlyStandAloneJtaPlatform
spring.jpa.properties.hibernate.transaction.coordinator_class=jta

#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false