spring.application.name=immobilier

server.servlet.context-path=/immobilier

# Schéma PostgreSQL par défaut
spring.jpa.properties.hibernate.default_schema=immonet

# Profil actif
spring.profiles.active=dev

# Encodage
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Internationalisation
spring.messages.basename=messages,org.hibernate.validator.ValidationMessages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
spring.web.locale=fr
spring.web.locale-resolver=fixed

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
