server.port=8383

spring.datasource.url=jdbc:postgresql://localhost:5432/immonet
spring.datasource.username=immonet
spring.datasource.password=immonet

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logs detailles pour debug
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
# Thymeleaf
spring.thymeleaf.cache=false

# Email de dev (ex: Mailtrap ou SMTP local)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nahouadioni19@gmail.com
spring.mail.password=fxsfahnjubmyehzb 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp

# Stockage fichiers
app.storage.directory=C:/opt/immobilier/dossiers